"""change file name

Revision ID: 1f67e9614c0f
Revises: ed198dc2afe8
Create Date: 2023-12-16 01:09:43.813248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f67e9614c0f'
down_revision = 'ed198dc2afe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_upload', sa.Column('local_path', sa.String(length=1024), nullable=True))
    op.drop_column('file_upload', 'recording_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_upload', sa.Column('recording_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('file_upload', 'local_path')
    # ### end Alembic commands ###
