"""added celery model

Revision ID: 864045026e2f
Revises: bb310f731ade
Create Date: 2023-04-21 19:40:28.509528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "864045026e2f"
down_revision = "c3d9a260e572"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery",
        sa.Column(
            "celery_id",
            sa.String(length=128),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("task_id", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("celery_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery")
    # ### end Alembic commands ###
