"""add metadata

Revision ID: 91dede4a905b
Revises: d8f1b0f2c0e0
Create Date: 2024-01-11 23:31:41.278272

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '91dede4a905b'
down_revision = 'd8f1b0f2c0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("CREATE OR REPLACE VIEW user_details AS SELECT u.user_id,u.username,u.email,u.password,u.first_name,u.last_name, u.phone_number, up.preference_id,up.is_disabled, up.modified_at, u.is_email_verified, up.added_at  FROM \"user\" u JOIN user_preference up ON up.user_id=u.user_id;")
    # ### end Alembic commands ###
    op.execute("""
    INSERT INTO public."user" (user_id,username,email,"password",first_name,last_name,created_at,default_page,is_disabled,notifications_enabled,mfa_enabled,mfa_secret,phone_number,is_email_verified,country_id,last_active_at) VALUES ('8f3ee82d-fa40-42c1-84cd-2da215937c40','thinhle.ict',NULL,'Admin@1234','Thinh','Le','2024-01-11 17:04:06.087',NULL,false,NULL,false,NULL,NULL,false,NULL,'2024-01-12 12:29:01.594');
    """)
    insert_user_role = (
        "INSERT INTO public.user_role (role_id,role_name,role_description,created_on,is_deletable) VALUES "
        "('270325cc-0378-48f2-8b18-67e1c22a64c5','client','Client','2024-01-11 16:36:46.967',false),"
        "('b40ee1ae-5a12-487a-98cc-b6d07238e17a','admin','Admin','2024-01-11 16:36:46.967',false);"
    )
    op.execute(insert_user_role)
    op.execute("INSERT INTO public.user_role_mapping (user_id,role_id) VALUES ('8f3ee82d-fa40-42c1-84cd-2da215937c40','b40ee1ae-5a12-487a-98cc-b6d07238e17a');")
    op.execute("INSERT INTO public.teams (teams_id,teams_name,teams_code,\"owner\",created_at,updated_at,is_disabled,is_deleted) VALUES ('791492c7-112b-49b4-9788-cb48160b45eb','Default','Default','8f3ee82d-fa40-42c1-84cd-2da215937c40','2024-01-11 17:04:06.087','2024-01-11 17:04:06.087',false,false);")
    op.execute("INSERT INTO public.user_teams_mapping (user_id,teams_id,is_default) VALUES ('8f3ee82d-fa40-42c1-84cd-2da215937c40','791492c7-112b-49b4-9788-cb48160b45eb',true);")
    pass


def downgrade():
    op.execute("DELETE FROM public.user_teams_mapping WHERE user_id='8f3ee82d-fa40-42c1-84cd-2da215937c40' AND teams_id='791492c7-112b-49b4-9788-cb48160b45eb'")
    op.execute("DELETE FROM public.teams WHERE teams_id='791492c7-112b-49b4-9788-cb48160b45eb'")
    op.execute("DELTETE FROM public.user_role_mapping WHERE user_id='8f3ee82d-fa40-42c1-84cd-2da215937c40' AND role_id='b40ee1ae-5a12-487a-98cc-b6d07238e17a'")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("DROP VIEW IF EXISTS user_details;")
    # ### end Alembic commands ###
    pass
