"""add metadata

Revision ID: 91dede4a905b
Revises: d8f1b0f2c0e0
Create Date: 2024-01-11 23:31:41.278272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dede4a905b'
down_revision = 'd8f1b0f2c0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("CREATE OR REPLACE VIEW user_details AS SELECT u.user_id,u.username,u.email,u.password,u.first_name,u.last_name, u.phone_number, up.preference_id,up.is_disabled, up.modified_at, u.is_email_verified, up.added_at  FROM \"user\" u JOIN user_preference up ON up.user_id=u.user_id;")
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("DROP VIEW IF EXISTS user_details;")
    # ### end Alembic commands ###
    pass
