"""Added events model

Revision ID: a16283a5bc21
Revises: e9a047c5d9fa
Create Date: 2024-01-24 17:53:27.355290

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a16283a5bc21"
down_revision = "e9a047c5d9fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.String(length=128), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=True),
        sa.Column("profile_id", sa.String(length=128), sa.ForeignKey("profiles.profile_id"), nullable=False),
        sa.Column("profile_id_interact", sa.String(length=128), sa.ForeignKey("profiles.profile_id"), nullable=True),
        sa.Column("schedule_id", sa.String(length=128), sa.ForeignKey("mission_schedule.schedule_id"), nullable=True),
        sa.Column("mission_id", sa.String(length=128), sa.ForeignKey("mission.mission_id"), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
