"""add chunks table

Revision ID: a744527074aa
Revises: 1f67e9614c0f
Create Date: 2023-12-17 00:10:13.715715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a744527074aa'
down_revision = '1f67e9614c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_chunks',
    sa.Column('id', sa.String(length=128), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False, server_default="false"),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=128), nullable=False, comment='the main file, chunks are split using this file'),
    sa.ForeignKeyConstraint(['parent_id'], ['file_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_chunks')
    # ### end Alembic commands ###
