"""add full text note

Revision ID: caaf5832fd24
Revises: a744527074aa
Create Date: 2023-12-20 21:51:13.107942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caaf5832fd24'
down_revision = 'a744527074aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('file_upload', sa.Column('full_text_result', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_upload', 'full_text_result')
    op.alter_column('file_chunks', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
