"""add file upload model

Revision ID: ed198dc2afe8
Revises: cbb01f1b3707
Create Date: 2023-12-16 00:51:48.057554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed198dc2afe8'
down_revision = 'cbb01f1b3707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_upload',
    sa.Column('id', sa.String(length=128), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=True),
    sa.Column('speech_path', sa.String(length=1024), nullable=True),
    sa.Column('recording_path', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('meeting_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_upload')
    # ### end Alembic commands ###
